### ISSUE TITLE
When we authenticate non administrators access user, throwing SEC_E_LOGON_DENIED error

### ISSUE THREAD

**Issue by RAMABATHIRANK** [jlguenego/node-expose-sspi#18]
Here below created user as 'shree' and assigned to 'test-group'. This user not assigned 'Administrators' group. During the auth method call throws the below error. Whereas the user assigned to 'Administrators' group working as fine.

How we can auth without  'Administrators' group added?

![Capture](https://user-images.githubusercontent.com/45968405/84170840-b57eef80-aa97-11ea-91e9-e76b1ef07325.JPG)

Error: AcceptSecurityContext error: SEC_E_LOGON_DENIED
    at Object.<anonymous> (C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:142:35)
    at step (C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:33:23)
    at Object.next (C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:14:53)
    at C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:4:12)
    at C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:86:31
    at C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:180:15
    at Layer.handle [as handle_request] (C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\express\lib\router\index.js:317:13)
BadRequestError: Error while doing SSO: AcceptSecurityContext error: SEC_E_LOGON_DENIED
    at Object.<anonymous> (C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:175:54)
    at step (C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:33:23)
    at Object.next (C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:14:53)
    at C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:4:12)
    at C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:86:31
    at C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\node-expose-sspi\dist\sso\auth.js:180:15
    at Layer.handle [as handle_request] (C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\GITHIKASHREE\VertX\OFFLINE-TEMPLATE-ENGINE\window-user\node_modules\express\lib\router\index.js:317:13)

**Comment by jlguenego** [comment]
I am going to investigate this use case and come back to you.

**Comment by jlguenego** [comment]
[According this url](https://microsoft.public.platformsdk.security.narkive.com/T18aDF1x/acceptsecuritycontext-returns-sec-e-logon-denied), there is a problem elsewhere with your account conf in your domain. The node-expose-sspi is outside the issue.

However, starting with 0.1.32 (released today) the node-expose-sspi module manage the SEC_E_LOGON_DENIED with 401 error, which is more what a user may need.

Closing this defect.

**Comment by RAMABATHIRANK** [comment]
Thanks, will check and let you know the same.
