### ISSUE TITLE
Your PC will automatically restart in one minute - SECURITY_STATUS incorrect (<0): (error code: 0x80090304) The Local Security Authority cannot be contacted

### ISSUE THREAD

**Issue by kirankumarch21** [jlguenego/node-expose-sspi#37]
**I have installed my application on the windows server and when I try to access the application from another system using the hostname of the server. I am getting below error** 

```
`Error: AcceptSecurityContext: SECURITY_STATUS incorrect (<0): (error code: 0x80090304) The Local Security Authority cannot be contacted

 at Object.<anonymous> (C:\inetpub\wwwroot\code\api\node_modules\node-expose-sspi\dist\sso\auth.js:152:60)
at step (C:\inetpub\wwwroot\code\api\node_modules\node-expose-sspi\dist\sso\auth.js:33:23)
at Object.next (C:\inetpub\wwwroot\code\api\node_modules\node-expose-sspi\dist\sso\auth.js:14:53)
at fulfilled (C:\inetpub\wwwroot\code\api\node_modules\node-expose-sspi\dist\sso\auth.js:5:58)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5072) UnhandledPromiseRejectionWarning: Error: GetUserNameEx: error first call. (error code: 0x000006ba) The RPC server is unavailable.

 at Object.getDefaultDomain (C:\inetpub\wwwroot\code\api\node_modules\node-expose-sspi\dist\sso\domain.js:11:26)
at Object.getStatusInfo (C:\inetpub\wwwroot\code\api\node_modules\node-expose-sspi\dist\sso\status.js:8:29)
at Object.<anonymous> (C:\inetpub\wwwroot\code\api\node_modules\node-expose-sspi\dist\sso\auth.js:202:64)
at step (C:\inetpub\wwwroot\code\api\node_modules\node-expose-sspi\dist\sso\auth.js:33:23)
at Object.next (C:\inetpub\wwwroot\code\api\node_modules\node-expose-sspi\dist\sso\auth.js:14:53)
at fulfilled (C:\inetpub\wwwroot\code\api\node_modules\node-expose-sspi\dist\sso\auth.js:5:58)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
```

**Your PC will automatically restart in one minute and PC is getting restarted every time I access it.**

Version : 0.1.39

Please let me know for any further information.

Regards,
Kiran

**Comment by jlguenego** [comment]
accepted. getStatusInfo should have a try catch

**Comment by kirankumarch21** [comment]
When will this change available for us?

**Comment by kirankumarch21** [comment]
@jlguenego we are waiting for your build. Could you please provide the build with this fix.

**Comment by jlguenego** [comment]
The try catch problem in getStatusInfo is fixed. So the server must not crash for not catched promise.

That being said, you should investigate why your windows os was rejecting the `(error code: 0x000006ba) The RPC server is unavailable`. I suggest you look on google. For instance this link:
https://www.auslogics.com/en/articles/fixing-the-rpc-server-is-unavailable-error-in-windows/

Ready for test. try version 0.1.41.
